### ISSUE TITLE
Mount point of LVM Volume is to specific

### ISSUE THREAD

**Issue by cmahnke** [easimon/maximize-build-space#29]
The action is a great tool, bit it has a minor drawback. 
The freed space is mounted the following way (output of the action itself, name of the repository changed)
```
/dev/mapper/buildvg-buildlv   39G   24K   39G   1% /home/runner/work/repo/repo
```
But I sometimes get the following message
```
System.IO.IOException: No space left on device : /home/runner/runners/2.308.0/_diag/Worker_20230912-055007-utc.log
```
[truncated]

I know, that I can change the free space of the root partition, but this doesn't really scale in terms in reusing the configuration in different projects.

Why not just changing the mount point of `/dev/mapper/buildvg-buildlv` to `/home/runner/`?

**Comment by easimon** [comment]
By default, the complete build (checkout, compilation artifacts etc.) happens in $GITHUB_WORKSPACE and subfolders of that. This is why I made this the default mountpoint, but you can change that: 

```
  build-mount-path:
    description: 'Absolute path to the mount point where the build space will be available, defaults to $GITHUB_WORKSPACE if unset.'
    required: false
```

But beware, the mount will make everything, that already exists in the mountpoint directory, inaccessible (which is, why this action should be the very first action in a workflow).

**Comment by cmahnke** [comment]
Great, thanks.
I'll have to see if changing it to the home path of the runner will affect it.
