### ISSUE TITLE
Mount path permissions

### ISSUE THREAD

**Issue by strickvl** [easimon/maximize-build-space#34]
Updates last night seem to have broken this action for me. https://github.com/zenml-io/zenml/actions/runs/7016996228/job/19090533966 you can see the error message. Was just running it with `build-mount-path: /var/lib/docker/` set. It was working without issue until last night / this morning.

When I rerun the action without setting that input to `var/lib/docker` the action itself works again / completes, but then I run out of space on integration tests etc that I'm trying to run on that runner.

So not quite sure about the diagnosis / root cause, but pretty sure it relates to the changes made overnight.

**Comment by easimon** [comment]
Thanks for being my canary :) In general, @master is not meant for daily use, but the released versions only.

Please test again, should be fixed with #35

**Comment by strickvl** [comment]
Got it. Testing `v8` version now and I'll test `@master` separately as well just to let you know. I assume I set it to `master` because that's the example given in the `README.md` file. Seems like there's no way to specify the version as `latest` unless you keep whatever version is latest tagged with that?

**Comment by strickvl** [comment]
Thank you for the quick fix / responsiveness!

**Comment by easimon** [comment]
> Got it. Testing `v8` version now and I'll test `@master` separately as well just to let you know. I assume I set it to `master` because that's the example given in the `README.md` file. Seems like there's no way to specify the version as `latest` unless you keep whatever version is latest tagged with that?

`v8` will work for you if it did previously -- that's what used to be `master` until yesterday. I'll release `v9` today.

I don't know of a direct way of pointing to the "latest release". But you can use dependabot to keep track of updates. Add a `.github/dependabot.yml` with content like this 

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

**Comment by strickvl** [comment]
TIL! Thanks for the tip. That's useful.
