### ISSUE TITLE
GitHub runners changes causes the root reserve argument to be non-functional

### ISSUE THREAD

**Issue by vyknight** [easimon/maximize-build-space#44]
After a recent GitHub runner change, which changed the file structure of the runners to remove `/mnt`, the root-reserve-mb flag no longer changes how much storage remains in the root directory. 

Old filesystem:
<img width="608" alt="image" src="https://github.com/easimon/maximize-build-space/assets/84593802/fb222596-4669-42cb-a828-4565e4037e3b">
Cleaner results on the old filesystem:
<img width="669" alt="image" src="https://github.com/easimon/maximize-build-space/assets/84593802/19ebe37d-74df-4848-92fe-0ef2ad3e4d6a">

New filesystem:
<img width="616" alt="image" src="https://github.com/easimon/maximize-build-space/assets/84593802/9140300b-c01f-4e43-a093-9b8e2dc61b9e">
Cleaner results on the new filesystem:
<img width="666" alt="image" src="https://github.com/easimon/maximize-build-space/assets/84593802/5f129b77-bfd2-4d41-8840-534ba4e3c0cb">

Arguments:
<img width="443" alt="image" src="https://github.com/easimon/maximize-build-space/assets/84593802/ee093270-d2c3-4c42-bc34-287bbcfbac7f">
Note that the arguments we used with the old file system is identical to this except `root-reserve-mb` was set to 30000.

**Comment by easimon** [comment]
Oh, that is unfortunate. GitHub has been changing runners quite a lot in the recent past. 

TBH, without the second partition, this action is not very useful anymore. The main aspect was to join the free space on / and /mnt. Without a /mnt, there is nothing to add.

The second feature (removing unused software using rm -rf) is something everybody can do way more flexible without the action.

I will try to dig into this, but without a second partition, I guess this action can be trashed...

**Comment by vyknight** [comment]
This is sad to hear, your action has been useful and reliable all this time.
Thanks for responding, I'll close this issue but we'll see if they ever bring back /mnt on another unannounced update.
