### ISSUE TITLE
swapoff: Not superuser

### ISSUE THREAD

**Issue by adammwilson** [easimon/maximize-build-space#9]
Thanks for this useful action!

I'm currently getting the following error: 

```
Unmounting and removing swap file.
swapoff: Not superuser.
Error: Process completed with exit code 1.
```

I find this confusing as I thought all actions were run as `root`.  Any ideas what's happening here?  Here's the [repository](https://github.com/AdamWilsonLab/emma_model/runs/5512497479?check_suite_focus=true#step:4:49).

Full actions log  is below.

Thanks for any help!

```
Run easimon/maximize-build-space@master
with:
    remove-dotnet: true
    remove-android: true
    remove-haskell: true
    root-reserve-mb: 1024
    temp-reserve-mb: 100
    swap-size-mb: 4096
    overprovision-lvm: false
    pv-loop-path: /pv.img
    tmp-pv-loop-path: /mnt/tmp-pv.img
  env:
    GITHUB_PAT: ***
Run echo "Memory and swap:"
Memory and swap:
              total        used        free      shared  buff/cache   available
Mem:        7116968      570596      347668       32492     6198704     6203892
Swap:       4194300        2316     4191984

NAME          TYPE SIZE USED PRIO
/mnt/swapfile file   4G 2.3M   -2

Available storage:
Filesystem      Size  Used Avail Use% Mounted on
overlay          84G   56G   29G  67% /
tmpfs            64M     0   64M   0% /dev
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/sda1        84G   56G   29G  67% /__w
tmpfs           696M  780K  695M   1% /run/docker.sock
tmpfs           3.4G     0  3.4G   0% /proc/acpi
tmpfs           3.4G     0  3.4G   0% /proc/scsi
tmpfs           3.4G     0  3.4G   0% /sys/firmware

Run set -euo pipefail
Arguments:

  Root reserve:      1024 MiB
  Temp reserve:      100 MiB
  Swap space:        96 MiB
  Overprovision LVM: false
  Mount path:        /__w/emma_model/emma_model
  Root PV loop path: /pv.img
  Temp PV loop path: /mnt/tmp-pv.img
  Removing:     dotnet android haskell 
Removing unwanted software... 
... done
Unmounting and removing swap file.
swapoff: Not superuser.
Error: Process completed with exit code 1.
```

**Comment by easimon** [comment]
You're running the action inside a container, not in the VM directly. And this runs as whatever user the image uses.

And there are other reasons why running this action in a container most probably fails: it most probably does not see the VMs mounts, and even if it does, I am unsure if it's running privileged, which is required to fiddle with file systems and mounts. And you most probably also don't have the required tools (LVM etc) in the image.

Better: run the action on the VM directly, as the very first build step. The way this action works, it mounts something on top of your work tree, which will then be empty, even if you e.g. checked out sources in a previous step.

**Comment by easimon** [comment]
Will close this issue, since using it in container-based actions is most probably not implementable -- but also unnecessary. You can just run this action on the VM directly, and then start container-based actions afterwards.
